- name: users | lbic | create ssh keys dir
  tags: ssh,ssh-keys
  file:
    path: /home/lbic/.ssh
    state: directory
    owner: lbic
    group: lbic
    mode: 0700

#- name: users | lbic | generate ssh keys
#  tags: ssh,ssh-keys
#  openssh_keypair:
#    path: /home/lbic/.ssh/id_ed25519
#    type: ed25519
#    state: present
#    owner: lbic
#    group: lbic
#    comment: "{{ ansible_facts['hostname'] }}"

- name: users | lbic | create known_hosts & authorized_keys files
  tags: ssh,ssh-keys
  copy:
    content: ""
    dest: "{{ item }}"
    force: no
    owner: lbic
    group: lbic
    mode: 0600
  with_items:
    - /home/lbic/.ssh/known_hosts
    - /home/lbic/.ssh/authorized_keys

- name: users | lbic | copy ssh keys
  tags: ssh,ssh-keys
  ansible.posix.authorized_key:

    user: lbic
    state: present
    manage_dir: true
    key: "{{ lookup('file', item.path) }}"
    comment: "{{ item.comment }}"
  with_items:
    - { path: "{{ role_path }}/files/ssh-keys/catuaba.pub", comment: "catuaba" }
