- name: development | git | install git & gh
  tags: dev,git
  package:
    name:
      - git
      - github-cli

- name: development | git | config settings
  tags: dev,git
  become_user: rafael
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: "user.name",          value: "Rafael Ito" }
    - { name: "user.email",         value: "ito.rafael@gmail.com" }
    - { name: "core.editor",        value: "vim" }
    - { name: "init.defaultBranch", value: "main" }
    - { name: "merge.ours.driver",  value: "true" }
    - { name: "color.ui",           value: "auto" }
