- name: development | git | install git & gh
  tags: dev,git
  package:
    name:
      - git
      - github-cli

- name: development | git | config user.name
  tags: dev,git
  become_user: rafael
  git_config:
    name: user.name
    value: "Rafael Ito"
    scope: global

- name: development | git | config user.email
  tags: dev,git
  become_user: rafael
  git_config:
    name: user.email
    value: "ito.rafael@gmail.com"
    scope: global

- name: development | git | config core.editor
  tags: dev,git
  become_user: rafael
  git_config:
    name: core.editor
    value: "vim"
    scope: global
