- name: software | IoT | install Saleae's logic analyzer tool
  tags: iot,logic-analyzer
  become_user: aurman
  kewlfft.aur.aur:
    name:
      #- saleae-logic
      - saleae-logic2
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | IoT | install Espressif esptool.py script
  tags: iot,esptool
  package:
    name: esptool

- name: software | IoT | install PlatformIO CLI
  tags: iot,platformio
  package:
    name:
      - platformio-core
      - platformio-core-udev
