- name: development | python | install Python
  tags: dev,python
  package:
    name: python

- name: development | python | install Python essential packages
  tags: dev,python
  package:
    name:
      - twine         # PyPI interaction
      - python-build  # PyPI build
      - python-pip    # PyPA packages install

- name: development | python | install Python miscellaneous packages
  tags: dev,python
  package:
    name:
      - python-pyserial  # serial port module

- name: development | python | install Python documentation packages
  tags: dev,python
  package:
    name:
      - python-sphinx            # Sphinx: documentation generator
      - python-sphinx_rtd_theme  # Read the Docs Sphinx theme
      - python-recommonmark      # markdown parser for docutils & Sphinx

- name: development | python | install Python data science packages
  tags: dev,python
  package:
    name:
      - python-numpy             # NumPy: arrays support
      - python-pandas            # pandas: data analysis (DataFrame object)
      - python-matplotlib        # Matplotlib: plot & visualization
      - python-scipy             # SciPy: scientific computing
      - python-scikit-learn      # scikit-learn: machine learning lib
      - python-seaborn           # seaborn: statistical data visualization
