- name: development | python | install Python
  tags: dev,python
  package:
    name: python

- name: development | python | install Python essential packages
  tags: dev,python
  package:
    name:
      - twine         # PyPI interaction
      - python-build  # PyPI build
      - python-pip    # PyPA packages install

- name: development | python | install Python miscellaneous packages
  tags: dev,python
  package:
    name:
      - python-pyserial  # serial port module
