- name: dev | terminal multiplexer | install tmux
  tags: terminal-multiplexer,tmux
  package:
    name: tmux

- name: dev | terminal multiplexer | ensure tmux dir exist
  tags: terminal-multiplexer,tmux
  file:
    path: /home/rafael/.config/tmux
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: dev | terminal multiplexer | copy tmux dotfile
  tags: terminal-multiplexer,tmux
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/tmux/tmux.conf
    dest: /home/rafael/.config/tmux/tmux.conf
    owner: rafael
    group: rafael
    mode: 0600
