- name: software | file manager | install GUI file manager
  tags: file-manager,thunar
  package:
    name:
      - thunar                  # Xfce file manager
      - tumbler                 # thumbnail support
      - ffmpegthumbnailer       # video thumbnailing
      - thunar-archive-plugin   # archive support frontend
      - xarchiver               # archive support backend

- name: software | file manager | install terminal file manager
  tags: file-manager,ranger
  package:
    name:
      - ranger

- name: software | file manager | ensure xfce4 dir exist
  tags: file-manager,thunar
  file:
    path: /home/rafael/.config/xfce4
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
