- name: software | file manager | install GUI file manager
  tags: file-manager,thunar
  package:
    name:
      - thunar                  # Xfce file manager
      - tumbler                 # thumbnail support
      - ffmpegthumbnailer       # video thumbnailing
      - thunar-archive-plugin   # archive support frontend
      - xarchiver               # archive support backend

- name: software | file manager | install terminal file manager
  tags: file-manager,ranger
  package:
    name:
      - ranger

- name: software | file manager | ensure xfce4 dir exist
  tags: file-manager,thunar
  file:
    path: /home/rafael/.config/xfce4
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | file manager | copy Thunar dotfiles
  tags: file-manager,thunar
  copy:
    remote_src: yes
    src: /home/ansible/git/dotfiles/{{ item.src }}
    dest: /home/rafael/.config/{{ item.dest }}
    owner: rafael
    group: rafael
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'xfce4/helpers.rc', dest: 'xfce4/helpers.rc', mode: '0700' }  # Thunar's "Open Terminal Here"
