#- name: software | media | install music streaming applications
#  tags: media,spotify
#  become_user: aurman
#  kewlfft.aur.aur:
#    name:
#      - spotify
#      - youtube-music-bin
#      - spotube-bin
