- name: software | miscellaneous | IRPF Brazilian income tax program
  tags: miscellaneous,irpf
  become_user: aurman
  aur:
    name: irpf

- name: software | miscellaneous | bank BB
  tags: miscellaneous,bank
  become_user: aurman
  aur:
    name: warsaw-bin
