- name: software | social-media | prevent packages conflict
  tags: social-media
  package:
    name:
      - slack-desktop  # Slack
    state: absent

- name: software | social-media | install applications from AUR
  tags: social-media
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - wasistlos              # WhatsApp
      - slack-desktop-wayland  # Slack

- name: software | social-media | install applications
  tags: social-media
  package:
    name:
      - discord
