- name: software | utils | install CLI tools
  tags: utils,general
  package:
    name:
      - bc              # calculator language
      - curl            # transfer data
      - dex             # DesktopEntry Execution
      - fzf             # fuzzy finder
      - imagemagick     # image manipulation with ImageMagick
      - libinput-tools  # input device mgmt + event lib (debug)
      - lsof            # lists open files for Unix processes
      - man-db          # full documentation
      - ntfs-3g         # NTFS fs driver
      - shfmt           # format shell scripts
      - sudo            # exec commands as another user
      - tldr            # TL;DR documentation
      - unrar           # RAR uncompression
      - unzip           # zip archives extraction
      - wget            # download files from web
      - whois           # provides mkpasswd

#- name: software | utils | install CLI tools (AUR)
#  tags: utils,general
#  become_user: aurman
#  kewlfft.aur.aur:
#    name:
#      - forx         # currencies exchange rates
#  when: ansible_facts['distribution'] == "Archlinux"

- name: software | utils | modern-unix
  tags: utils,modern-unix
  package:
    name:            # replacement for:
      - bat          # cat
      - eza          # ls
      - zoxide       # cd
  # https://github.com/ibraheemdev/modern-unix

- name: software | utils | install GUI tools
  tags: utils,tools
  package:
    name:
      - gimp         # image editor
      - meld         # GUI diff
      - pdfpc        # slides presentation
      - yad          # GUI dialogs from CLI/scripts (zenity fork)

- name: software | utils | install GUI tools (AUR)
  tags: utils,tools
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - localsend-bin  # share files/messages over LAN
      - warpd          # keyboard-driven mouse cursor manipulation
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | utils | copy LocalSend dotfile
  tags: utils,tools
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/localsend/settings.json
    dest: /opt/localsend/settings.json
    owner: rafael
    group: rafael
    mode: 0600
  when: ansible_facts['distribution'] == "Archlinux"
