- name: software | utils | install CLI tools
  tags: utils,general
  package:
    name:
      - sudo         # exec commands as another user
      - wget         # download files from web
      - curl         # transfer data
      - lsof         # lists open files for Unix processes
      - man-db       # full documentation
      - tldr         # TL;DR documentation
      - imagemagick  # image manipulation with ImageMagick
      - fzf          # fuzzy finder
      - bc           # calculator language
      - dex          # DesktopEntry Execution
      - unrar        # RAR uncompression
      - unzip        # zip archives extraction

#- name: software | utils | install CLI tools (AUR)
#  tags: utils,general
#  become_user: aurman
#  kewlfft.aur.aur:
#    name:
#      - forx         # currencies exchange rates
#  when: ansible_facts['distribution'] == "Archlinux"

- name: software | utils | modern-unix
  tags: utils,modern-unix
  package:
    name:            # replacement for:
      - bat          # cat
      - eza          # ls
      - zoxide       # cd
  # https://github.com/ibraheemdev/modern-unix

- name: software | utils | install GUI tools
  tags: utils,tools
  package:
    name:
      - gimp         # image editor
      - pdfpc        # slides presentation
      - meld         # GUI diff
      - yad          # GUI dialogs from CLI/scripts (zenity fork)

- name: software | utils | install GUI tools (AUR)
  tags: utils,tools
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - warpd          # keyboard-driven mouse cursor manipulation
      - localsend-bin  # share files/messages over LAN
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | utils | copy LocalSend dotfile
  tags: utils,tools
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/localsend/settings.json
    dest: /opt/localsend/settings.json
    owner: rafael
    group: rafael
    mode: 0600
  when: ansible_facts['distribution'] == "Archlinux"
