- name: system | audio | Sound Open Firmware driver
  tags: audio,sof
  package:
    name: sof-firmware        # for drivers built with Sound Open Firmware

- name: system | audio | ALSA utilities install
  tags: audio,pipewire
  package:
    name: alsa-utils          # alsamixer, amixer, etc

- name: system | audio | PipeWire install
  tags: audio,pipewire
  package:
    name: 
      - pipewire
      - pipewire-docs

- name: system | audio | WirePlumber session manager
  tags: audio,pipewire
  package:
    name: wireplumber

- name: system | audio | PipeWire ALSA API
  tags: audio,pipewire
  package:
    name: pipewire-alsa

- name: system | audio | PipeWire JACK support
  tags: audio,pipewire
  package:
    name: pipewire-jack

- name: system | audio | Helvum (GTK patchbay for PipeWire)
  tags: audio,pipewire
  package:
    name: helvum

- name: system | audio | PipeWire replacement for PulseAudio (Bluetooth)
  tags: audio,pipewire
  package:
    name: pipewire-pulse

- name: system | audio | install pavucontrol (PulseAudio Volume Control)
  tags: audio,pipewire
  package:
    name: pavucontrol

- name: system | audio | install CAVA (Cross-platform Audio Visualizer)
  tags: audio,cava
  package:
    name: cava  # bar spectrum audio visualizer for terminal
