- name: system | CPU | install Intel microcode
  tags: system,cpu
  package:
    name: intel-ucode
  when: ansible_processor[1] == 'GenuineIntel'

- name: system | CPU | install AMD microcode
  tags: system,cpu
  package:
    name: amd-ucode
  when: ansible_processor[1] == 'AuthenticAMD'
