- name: system | fs | install BTRFS utilities
  tags: system,fs,btrfs
  package:
    name:
      - snapper          # manage BTRFS and LVM snapshots
      - btrfs-assistant  # manage BTRFS subvolumes and Snapper snapshots
