- name: system | fonts | install fonts
  tags: system,fonts
  package:
    name:
      - ttf-jetbrains-mono              # JetBrains Mono
      - ttf-font-awesome                # Font Awesome: iconic font designed for Bootstrap (woff2 format)
      - otf-font-awesome                # Font Awesome: iconic font designed for Bootstrap (otf format) (used by Waybar)
      - ttf-firacode-nerd               # Nerd Fonts: Fira (Fura) Code (used by Waybar)
      - ttf-ubuntu-font-family          # Ubuntu Font Family

- name: system | fonts | install fonts from AUR
  tags: system,fonts
  become_user: aurman
  kewlfft.aur.aur:
    name: ttf-all-the-icons  # used by Emacs
  when: ansible_facts['distribution'] == "Archlinux"

- name: system | fonts | install Font Manager
  tags: system,fonts
  package:
    name:
      - font-manager

- name: system | fonts | install emoji picker
  tags: system,fonts
  become_user: aurman
  kewlfft.aur.aur:
    name: emote
  when: ansible_facts['distribution'] == "Archlinux"
