- name: system | GPU AMD | install requirements to run Vulkan applications
  tags: system,gpu,gpu-amd
  package:
    name:
      - vulkan-icd-loader        # Installable Client Driver (ICD) Loader
      - lib32-vulkan-icd-loader  # ICD for 32-bit applications (requires multilib repository)
      - vulkan-tools             # Vulkan tools and utilities
      - vulkan-radeon            # provides vulkan-driver
      - lib32-vulkan-radeon      # provides lib32-vulkan-driver

- name: system | GPU AMD | install ROCm-related packages
  tags: system,gpu,gpu-amd
  package:
    name:
      - rocm-core  # core package
      - amdsmi     # AMD system management interface
