- name: system | network | install network packages
  tags: system,network
  package:
    name:
      - net-tools  # collection of base networking utilities
      - inetutils  # collection of common network programs

- name: system | network | install NetworkManager
  tags: system,network
  package:
    name:
      - networkmanager          # core package
      - nm-connection-editor    # GUI
      - network-manager-applet  # system tray applet

- name: system | network | start NetworkManager daemon
  tags: system,network
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: system | network | install Avahi
  tags: system,network
  package:
    name: avahi

- name: system | network | start Avahi daemon
  tags: system,network
  systemd:
    name: avahi-daemon
    state: started
    enabled: yes
